//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.04 at 03:02:10 PM PST 
//


package gov.hhs.onc.pdti.server.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.hhs.onc.pdti.server.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FederatedRequestData_QNAME = new QName("", "FederatedRequestData");
    private final static QName _SearchResultEntryMetadata_QNAME = new QName("", "SearchResultEntryMetadata");
    private final static QName _FederatedSearchResponseData_QNAME = new QName("", "FederatedSearchResponseData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.hhs.onc.pdti.server.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FederatedRequestData }
     * 
     */
    public FederatedRequestData createFederatedRequestData() {
        return new FederatedRequestData();
    }

    /**
     * Create an instance of {@link SearchResultEntryMetadata }
     * 
     */
    public SearchResultEntryMetadata createSearchResultEntryMetadata() {
        return new SearchResultEntryMetadata();
    }

    /**
     * Create an instance of {@link FederatedSearchResponseData }
     * 
     */
    public FederatedSearchResponseData createFederatedSearchResponseData() {
        return new FederatedSearchResponseData();
    }

    /**
     * Create an instance of {@link FederatedResponseStatus }
     * 
     */
    public FederatedResponseStatus createFederatedResponseStatus() {
        return new FederatedResponseStatus();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FederatedRequestData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FederatedRequestData")
    public JAXBElement<FederatedRequestData> createFederatedRequestData(FederatedRequestData value) {
        return new JAXBElement<FederatedRequestData>(_FederatedRequestData_QNAME, FederatedRequestData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchResultEntryMetadata }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SearchResultEntryMetadata")
    public JAXBElement<SearchResultEntryMetadata> createSearchResultEntryMetadata(SearchResultEntryMetadata value) {
        return new JAXBElement<SearchResultEntryMetadata>(_SearchResultEntryMetadata_QNAME, SearchResultEntryMetadata.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FederatedSearchResponseData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FederatedSearchResponseData")
    public JAXBElement<FederatedSearchResponseData> createFederatedSearchResponseData(FederatedSearchResponseData value) {
        return new JAXBElement<FederatedSearchResponseData>(_FederatedSearchResponseData_QNAME, FederatedSearchResponseData.class, null, value);
    }

}
